export const API_KEY_SIGNUP_URLS = {
  nvidia: 'https://build.nvidia.com/',
  groq: 'https://console.groq.com/',
  cerebras: 'https://cloud.cerebras.ai/',
  anthropic: 'https://console.anthropic.com/',
  opencode: 'https://opencode.ai/auth',
  openai: 'https://platform.openai.com/api-keys',
  'openai-compatible': 'https://platform.openai.com/docs/api-reference/chat',
  openrouter: 'https://openrouter.ai/settings/keys',
  codestral: 'https://codestral.mistral.ai/',
  scaleway: 'https://console.scaleway.com/iam/api-keys',
  qwencode: 'https://modelstudio.console.alibabacloud.com/',
  kilocode: 'https://kilo.ai/',
  googleai: 'https://aistudio.google.com/apikey',
  gemini: 'https://aistudio.google.com/apikey',
}
